config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users, controllers: {
      sessions: 'users/sessions'
      }
  resources :carros do resources :conductors
  end
  get "/", to: "carros#index"
  get "users/list", to: "carros#user", as: "list_user"
    root to: 'carros#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carro.rb
class Carro < ApplicationRecord
    has_many :conductors
    belongs_to :user, optional: true
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: [:show, :edit, :update, :destroy]

  # GET /carros
  # GET /carros.json
  def index
    @carros = Carro.all  
end

  # GET /carros/1
  # GET /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    #@carro = Carro.new
    #role= current_user.role
    #if role== "Chofer"
    #flash[:notice]= "No puede acceder a esta ruta" redirect_to carros_path
    #else
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros
  # POST /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: 'Carro was successfully created.' }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1
  # PATCH/PUT /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: 'Carro was successfully updated.' }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1
  # DELETE /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: 'Carro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carro_params
      params.require(:carro).permit(:marca, :modelo, :anio, :clase, :duenio)
    end
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carros/_form.html.erb
<%= form_with(model: carro, local: true) do |form| %>
  <% if carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% carro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca, id: :carro_marca %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo, id: :carro_modelo %>
  </div>

  <div class="field">
    <%= form.label :anio %>
    <%= form.number_field :anio, id: :carro_anio %>
  </div>

  <div class="field">
    <%= form.label :clase %>
    <%= form.select :clase, ['A','AA','AAA'], id: :carro_clase %>
  </div>

  <div class="field">
    <%= form.label :duenio %>
    <%= form.text_field :duenio, id: :carro_duenio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<h1>Carros</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Anio</th>
      <th>Clase</th>
      <th>Dueño</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.marca %></td>
        <td><%= carro.modelo %></td>
        <td><%= carro.anio %></td>
        <td><%= carro.clase %></td>
        <td><%= carro.duenio %></td>
        
        <% role= current_user.role%>
        <% if role == "Pasajero"%>
        <td class="button primary"><%= link_to 'Mostar Carro', carro %></td>
        <% elsif role =="Chofer"%>
        <td class="button primary"><%= link_to 'Mostar Carro', carro %></td>
        <td class="button warning"><%= link_to 'Editar', edit_carro_path(carro) %></td>
        <%else%>
        <td class="button primary"><%= link_to 'Mostar Carro', carro %></td>
        <td class="button warning"><%= link_to 'Editar', edit_carro_path(carro) %></td>
        <td class="button alert"><%= link_to 'Eliminar', carro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
    
  </tbody>
</table>

<br>
<% role= current_user.role%>
 <% if role == "Pasajero"%>
 <p></p>
 <%else%>
<%= link_to 'New Carro', new_carro_path %>
<% end %>
    

app/views/carros/new.html.erb
<h1>New Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<style>
p{
  font-size: 18px;
  
}
</style>
<br>
<table class="hover">
  <tr>
<td>
<p>
  <strong>Marca:</strong>
  <%= @carro.marca %>
</p>
</td>
<td>
<p>
  <strong>Modelo:</strong>
  <%= @carro.modelo %>
</p>
</td>
<td>
<p>
  <strong>Anio:</strong>
  <%= @carro.anio %>
</p>
</td>
<td>
<p>
  <strong>Clase:</strong>
  <%= @carro.clase %>
</p>
</td>
<td>
<p>
  <strong>Duenio:</strong>
  <%= @carro.duenio %>
</p>
</td>
</tr>
</table>
<div>

</div>
<br>
<table class="hover">

  <thead>
  <tr>
  <th>Nombre: </th>
  <th>Apellido: </th>
  <th>Correo: </th>
</tr>
</thead>

<% @carro.conductors.each do |carro| %>
<tr>
<td><%=carro.nombre %></td>
<td><%=carro.apellido %></td>
<td><%=carro.correo %></td>
</tr>
<% end %> 
<br>
<div>
<h4><small>Agrega un conductor al carro</small></h4>
</div>

<%= form_for([@carro, Conductor.new], remote: true) do |f| %>
  <div class="row">

  <div class="medium-6 columns">
  <%= f.label :nombre %>
    <%= f.text_field :nombre, id: :conductor_nombre %>
    </div>
  <div class="medium-6 columns">
    <%= f.label :apellido %>
    <%= f.text_field :apellido, id: :conductor_apellido %>
    </div>
 <div class="medium-6 columns">
    <%= f.label :correo %>
    <%= f.text_field :correo, id: :conductor_correo %>
  </div>
  <br>
<div classs="medium-6 columns">
<%= f.submit 'Crear Conductor', class:'hollow button secondary' %>
</div>
</div>
<% end %>
<%= link_to '<button class="button warning"> Editar Carro </button>'.html_safe, edit_carro_path(@carro) %> |
<%= link_to '<button class="button secondary"> Regresar </button>'.html_safe, carros_path %>
<h2><small>C O N D U C T O R E S </small></h2>  