config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users, controllers: {
      sessions: 'users/sessions'
      }
  resources :carros do resources :conductors
  end
  get "/", to: "carros#index"
  get "users/list", to: "carros#user", as: "list_user"
    root to: 'carros#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conductor.rb
class Conductor < ApplicationRecord
    belongs_to :carro, optional: true
end

app/controllers/conductors_controller.rb
class ConductorsController < ApplicationController
  before_action :set_conductor, only: [:show, :edit, :update, :destroy]

  # GET /conductors
  # GET /conductors.json
  def index
    @conductors = Conductor.all
  end

  # GET /conductors/1
  # GET /conductors/1.json
  def show
  end

  # GET /conductors/new
  def new
    @conductor = Conductor.new
    @carros = Carro.all
    
  end

  # GET /conductors/1/edit
  def edit
  end

  # POST /conductors
  # POST /conductors.json
  def create
   @carro = Carro.find(params[:carro_id]);
      @conductor = @carro.conductors.create(conductor_params);
    
    respond_to do |format|
      if @conductor.save
        format.html { redirect_to @conductor, notice: 'Conductor was successfully created.' }
        format.json { render :show, status: :created, location: @conductor }
      else
        format.html { render :new }
        format.json { render json: @conductor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conductors/1
  # PATCH/PUT /conductors/1.json
  def update
    respond_to do |format|
      if @conductor.update(conductor_params)
        format.html { redirect_to @conductor, notice: 'Conductor was successfully updated.' }
        format.json { render :show, status: :ok, location: @conductor }
      else
        format.html { render :edit }
        format.json { render json: @conductor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conductors/1
  # DELETE /conductors/1.json
  def destroy
    @conductor.destroy
    respond_to do |format|
      format.html { redirect_to conductors_url, notice: 'Conductor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conductor
      @conductor = Conductor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conductor_params
      params.require(:conductor).permit(:nombre, :apellido, :correo)
    end
end

app/helpers/conductors_helper.rb
module ConductorsHelper
end

app/views/conductors/_form.html.erb
<%= form_with(model: conductor, local: true) do |form| %>
  <% if conductor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conductor.errors.count, "error") %> prohibited this conductor from being saved:</h2>

      <ul>
      <% conductor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <% options = options_from_collection_for_select(Carro.all, 'id', 'name') %>
  <%= select_tag("conductor[carro_id]"), options)%>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :conductor_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, id: :conductor_apellido %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :conductor_correo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conductors/edit.html.erb
<h1>Editing Conductor</h1>

<%= render 'form', conductor: @conductor %>

<%= link_to 'Show', @conductor %> |
<%= link_to 'Back', conductors_path %>

app/views/conductors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conductors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conductors.each do |conductor| %>
      <tr>
        <td><%= conductor.nombre %></td>
        <td><%= conductor.apellido %></td>
        <td><%= conductor.correo %></td>
        <td><%= link_to 'Show', conductor %></td>
        <td><%= link_to 'Edit', edit_conductor_path(conductor) %></td>
        <td><%= link_to 'Destroy', conductor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conductor', new_conductor_path %>

app/views/conductors/new.html.erb
<h1>New Conductor</h1>

<%= render 'form', conductor: @conductor %>

<%= link_to 'Back', conductors_path %>

app/views/conductors/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @conductor.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @conductor.apellido %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @conductor.correo %>
</p>

<%= link_to 'Edit', edit_conductor_path(@conductor) %> |
<%= link_to 'Back', conductors_path %>