config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users, controllers: {
      sessions: 'users/sessions'
      }
  resources :carros do resources :conductors
  end
  get "/", to: "carros#index"
  get "users/list", to: "carros#user", as: "list_user"
    root to: 'carros#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <style>
  </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<%= image_tag 'LOGO.png' , class:'logo'%>
  <h1 class="titulo">GarageForceBrother</h1>
<% if user_signed_in? %> 
<div class="top-bar">
<div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>
              <li class="menu-text">
                  <a href="#">Menu</a>
                  <ul class="menu">
                      <%role= current_user.role%>
                      <% if role == "Pasajero"%>
                      <li><%= link_to "Mostrar Carros", carros_path %></li>
                      <% else%>
                      <li><%= link_to "Mostrar Carros", carros_path %></li>
                      <li><%= link_to "Agregar Nuevo Carro", new_carro_path %></li>
                      <%end%>
                      
                  </ul>
              </li>
          </ul>
      </div>
<%end%>
<div class="top-bar-right">
      <ul class="menu align-right">
      <% if user_signed_in? %>
        <li class="user">Nombre de ususario : <%= current_user.username%>  <br> <br>Rol: <%= current_user.role%> </li>
        <br>
        <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
        <li><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete%></li>
        <% else %>     
        <li class="button small success"><%= link_to "Login", new_user_session_path %></li>
        <li class="button small warning"><%= link_to "Registro", new_user_registration_path %></li>
        
            <%end%>
        </ul>    
      </div>
      </div> 

<br>
  <%if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <%end%>
<% if alert %>
      <p class="alert alert-danger"><%=alert%></p>
      <% end %>
 
    <%= yield %>

  </body>
</html>